[package]
name = "test_rust"
version = "0.1.0"
authors = ["Lucas Guillerot lguiller <lguiller@student.42.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.15"
